name: Ubuntu

on: [push]

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        run: curl -sL https://raw.githubusercontent.com/hedwig100/dotfiles/main/install.sh | sh